spring:
  application:
    name: notification-service
  mongodb:
    uri: ${SPRING_DATA_MONGODB_URI}

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: paymentGroup,orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.gsk.notification.kafka.order.OrderConfirmation,paymentConfirmation:com.gsk.notification.kafka.payment.PaymentConfirmation

  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}

    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

server:
  port: 9095

eureka:
  client:
    service-url:
      ## Comment datasource part when you are running docker-compose
#      defaultZone: http://service-registry:8761/eureka/
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}