spring:
  application:
    name: customer-service

  ## Comment datasource part when you are running docker-compose
#  datasource:
#    url: jdbc:mysql://localhost:3306/customer_db?useSSL=false&serverTimezone=UTC
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 9091

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/

  instance:
    prefer-ip-address: true
