server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

          routes:
            - id: customer-service
              uri: lb://customer-service
              predicates:
                - Path=/v1/customer/**

            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/v1/product/**

            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/v1/order/**

            - id: payment-service
              uri: lb://payment-service
              predicates:
                - Path=/v1/payment/**

            - id: notification-service
              uri: lb://notification-service
              predicates:
                - Path=/v1/notification/**

eureka:
  client:
    service-url:
      defaultZone: //service-registry:8761/eureka/

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"