spring:
  application:
    name: order-service
## Comment datasource part when you are running docker-compose
#  datasource:
#    url: jdbc:mysql://localhost:3306/order_db?useSSL=false&serverTimezone=UTC
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    openfeign:
      client:
        config:
          customer-service:
            url: ${CUSTOMER_SERVICE_URL}
#            url: http://localhost:9091

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:com.gsk.order.kafka.model.OrderNotificationRequest

application:
  config:
#    product-url: http://localhost:9090
    product-url: http://product-service:9090
server:
  port: 9093

eureka:
  client:
    service-url:
      ## Comment datasource part when you are running docker-compose
#     defaultZone: http://localhost:8761/eureka
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}